### ISSUE TITLE
hlc_clock_device_linux.go

### ISSUE THREAD

**Issue by 5k3105** [auxten/postgresql-parser#1]
github.com/auxten/postgresql-parser/pkg/util/hlc
../../auxten/postgresql-parser/pkg/util/hlc/hlc_clock_device_linux.go:51:11: cannot use ctx (type context.Context) as type string in argument to logrus.Infof

Using arch. Commented out that single log write on line 51 and 'log' import and the example worked.

Thanks!

**Comment by auxten** [comment]
Fixed
