### ISSUE TITLE
Dependency security warning

### ISSUE THREAD

**Issue by a631807682** [auxten/postgresql-parser#17]
I am getting a high severity security warning, can we update this dependency?

> Improper Input Validation in GoGo Protobuf

<table>
<tr>
	<td>Package
	<td>Affected versions
	<td>Patched version
<tr>
	<td>github.com/gogo/protobuf(Go)
	<td>< 1.3.2
	<td>1.3.2
</table>

An issue was discovered in GoGo Protobuf before 1.3.2. plugin/unmarshal/unmarshal.go lacks certain index validation, aka the "skippy peanut butter" issue.

**Comment by auxten** [comment]
yes, can you create a pull request for that?
