### ISSUE TITLE
syntax error: at or near "‹)›"

### ISSUE THREAD

**Issue by Kikkon** [auxten/postgresql-parser#21]
Hi
I'm currently facing an issue while use postgresql-parser. During my usage, I encountered an error with the following code snippet:

code:
```
	sql := "SELECT PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY id) FROM test_table"
	stmt, err := parser.ParseOne(sql)
```
error msg:
```
 "syntax error: at or near "‹)›"
```

 I'm not very familiar with the inner workings of the parser and would greatly appreciate any assistance you can provide. I'm more than willing to contribute code to fix this problem if you could kindly point me in the right direction.

**Comment by Kikkon** [comment]
🤣 I have discovered this is an unsupported syntax.

**Comment by auxten** [comment]
WITHIN is not common expr in SQL, which kinds of SQL dialect you are using?

**Comment by Kikkon** [comment]
> WITHIN is not common expr in SQL, which kinds of SQL dialect you are using?
> 
> WITHIN 不是 SQL 中常见的表达式，您使用的是哪种 SQL 方言？关闭

I'm using the Postgres SQL dialect, and I found that WITHIN is supported in the latest cockroach DB
