### ISSUE TITLE
How do I parse a given sql statement, and add where / order by / lilmit clauses to it?

### ISSUE THREAD

**Issue by vamshiaruru32** [auxten/postgresql-parser#25]
Hi! I am total beginner to this library and am unable to figure out how to add a where clause to a select statement. Is this library only meant for parsing and getting a tree, but not adding anything to that tree? 
Any help is appreciated, thank you.

**Comment by auxten** [comment]
Modifying the SQL AST is also ok. You can modify the AST and convert it to String.

**Comment by auxten** [comment]
Set a breakpoint after parsing SQL, and check the AST structure will help you understand how to modify it.
There is a relatively complex example of modifying the AST. https://github.com/auxten/go-sql-lineage/blob/main/lineage/normalize.go#L32
