### ISSUE TITLE
Licensing under apache 2.0?

### ISSUE THREAD

**Issue by saolof** [auxten/postgresql-parser#28]
Cockroach labs released the cockroachdb parser under an Apache 2.0 license a couple years ago since the parser is widely useful in third party support tools like LSPs:
https://github.com/cockroachdb/cockroachdb-parser

This may make it possible to make this project available under the more permissive and far more widely known Apache 2.0 license, so that other permissively licensed open-source projects can use it? Depending on how the initial code was pulled in, this may require checking in with Cockroach labs on their community slack to ensure that they are fine with it, but I would be rather surprised if they said no given the nature of this project.

**Comment by auxten** [comment]
I think changing license to Apache 2.0 is okay. I'll do it today.
